apiVersion: v1
kind: ConfigMap
metadata:
  name: environment-config
  namespace: bank-of-anthos
data:
  LOCAL_ROUTING_NUM: "883745000"
  PUB_KEY_PATH: "/tmp/.ssh/publickey"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-data-config
  namespace: bank-of-anthos
data:
  USE_DEMO_DATA: "True"
  DEMO_LOGIN_USERNAME: "testuser"
  DEMO_LOGIN_PASSWORD: "bankofanthos"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: oauth-config
  namespace: bank-of-anthos
data:
  DEMO_OAUTH_CLIENT_ID: ""
  DEMO_OAUTH_REDIRECT_URI: ""
