apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
  namespace: bank-of-anthos
  labels:
    app: loadgenerator
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: loadgenerator
  template:
    metadata:
      labels:
        app: loadgenerator
        tier: frontend
    spec:
      terminationGracePeriodSeconds: 5
      restartPolicy: Always
      containers:
        - name: loadgenerator
          image: us-central1-docker.pkg.dev/bank-of-anthos-ci/bank-of-anthos/loadgenerator:v0.6.8
          env:
            - name: FRONTEND_ADDR
              value: "http://frontend:80"
            - name: USERS
              value: "5"
            - name: LOG_LEVEL
              value: "info"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
