apiVersion: v1
kind: Secret
metadata:
  name: jwt-key
  namespace: bank-of-anthos
type: Opaque
stringData:
  jwtRS256.key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIEpAIBAAKCAQEAuMMVCOiTlnvw3p9w+B+4lBbXE3HLfT9fFxXqPvxHJ0nJJCEu
    W0gAFg7DAGUQhI5pJT8CJrPOuWmG+4/YCTQ8uYXUzSaMgJMKBuCzb2Q4E0PvMqFe
    YFMKCmZlLQKfB0FH9kG8K2E0jmz6uIe5jjXcJ3OyV3l2lBzVhxHKk3TJP0aGF4Wm
    7DgGDU7PJdX5h7D9Q6qW6B8xGfOBWfNpMbYQpCKm/WMbvFQ7B7lfwuWKzPXqJM0o
    HQnvbPCBBs7Z3/1h4bTx5J8jlLlC5JZ8oj6wHJJGO0vE5JfO7KlhBx5rZKf7hD7L
    rNj4r5PXfAJNdJy7UZofnJE6/gG+U9A7YJuPBwIDAQABAoIBAC9lFz+8N4EqjNQO
    Ut1NhABPayVXqF/K3T8qWL+NbWpvg6WmQI7B8vVUHNd8+7S4QHQQ6DJZJ6LZ4Nna
    aJFCQLD3G7a7gAC6nTvCYKvICIO39DoOag5wWwfJ0BkSVtAY7BVpNr2QuVVGcz8t
    NzY7MmE1kNlZPa2ChJv0T6hLF1EpqWMP+n3+k3N1tFUCQPNRUJQGnI7E7k4bL3nI
    lYBAXUV5qnShCTlkjXQxrMQ1y5TXN1BKPN3SRQDyV/YKE3jkYjICYiU0sFQVzLZp
    dKC8yXuKpINK6bYB5Y4V3PYx5XQ3R7IdPmY8cZF1VGdOCwyYzLas5xsrZDuKJ4bv
    po0o8CECgYEA5J5VXpUx8eig7S+EYFj9Q6lOZhK3TnQ7qpQm6B5C8YZC6f0hLmG3
    kpGN/2p4y1Lk9sQdIlnNxM/VxPP9rDZ6e8H3hDbWs6MxMN3pIKrh8sPGN5F6m8pc
    9Djx5eMRCuGPl/aDFXN9Z/hvZqMKkCV3GtGPe1LqlbWqV3bKUhmMgakCgYEAzvG5
    v9jVshYA+VtaLQGMHJYKrGG0BlLPFjvBCPMviCgyNhPHq9TxYbP3Cez+60WSQFMN
    +cygHOPv+rTaehHSq2L2s7H0kNKIb5W3SQ2t4E0wDpLkB/aFpuFaClL+I3cCgYA3
    OULG0JxmGNh2kzMETLYF7ARIITCQ0xMINLgC3nHiPmdnJe4hJ5aQoZl+PWBDFLS1
    9LW4k7y6M7kRqzN6aWdnFHPf0BTJQW/aJE1pQ3C5K7sMk0Qn6ZHQCQKO7Y0N0nae
    xGAEw6TqH7Dw2o+6KqaDHyM+OwBWMzCnYQ8UgQKBgQCuP/s7aJQ8VyY3W5wFP/pJ
    lWuBr4E7M0z0YBFPibEKC6LAeqmU6yClI5DjTu7hQKe1LCZhAZnCdZBNwKc3TEsg
    TZbwPMDXCd7VkPqNmITKvLLjeq7aJ7S8LnVIqCzgXwEILqLCTAtLwmqF5P8GO95H
    H3ozxTXREjyzd4WpJqg8gQKBgQCq7j9J1kk7z8DPJA0sLAKJ0EiTR7+GZqA+Kv0W
    dZSfMpJf8sXvPvQP3L5l8FDAaKYJxWPcO5bfhD7f7B4W7c9w+3e0H5l5z3Tp1nIo
    0KQN3cQf4hAMhYBQymEAeMfQ4T5LiJbPzj3ASNWMC0PLyrh7M0e8C0bvfL3hWb8l
    SiuaLQ==
    -----END RSA PRIVATE KEY-----
  jwtRS256.key.pub: |
    -----BEGIN PUBLIC KEY-----
    MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAuMMVCOiTlnvw3p9w+B+4
    lBbXE3HLfT9fFxXqPvxHJ0nJJCEuW0gAFg7DAGUQhI5pJT8CJrPOuWmG+4/YCTQ8
    uYXUzSaMgJMKBuCzb2Q4E0PvMqFeYFMKCmZlLQKfB0FH9kG8K2E0jmz6uIe5jjXc
    J3OyV3l2lBzVhxHKk3TJP0aGF4Wm7DgGDU7PJdX5h7D9Q6qW6B8xGfOBWfNpMbYQ
    pCKm/WMbvFQ7B7lfwuWKzPXqJM0oHQnvbPCBBs7Z3/1h4bTx5J8jlLlC5JZ8oj6w
    HJJGO0vE5JfO7KlhBx5rZKf7hD7LrNj4r5PXfAJNdJy7UZofnJE6/gG+U9A7YJuP
    BwIDAQAB
    -----END PUBLIC KEY-----
