apiVersion: v1
kind: Namespace
metadata:
  name: bank-of-anthos
  labels:
    app.kubernetes.io/name: bank-of-anthos
    app.kubernetes.io/part-of: ciroos-demo
    kubernetes.io/metadata.name: bank-of-anthos
